<a href="https://colab.research.google.com/github/dxxk/Udemy_ML_Bootcamp/blob/master/02_missing_values.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import sklearn
sklearn.__version__

'0.22.2.post1'

In [3]:
data = {
    'size': ['XL','L','M',np.nan,'M','M'],
    'color':['red', 'green','blue','green','red','green'],
    'gender':['female','male',np.nan,'female','female','male'],
    'price':[199.0, 89.0,np.nan, 129.0, 79.0,89.0],
    'weight':[500, 450, 300, np.nan, 410,np.nan],
    'bought':['yes','no','yes','no','yes','no']
}
df_raw = pd.DataFrame(data=data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

In [4]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   6 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  4 non-null      float64
 5   bought  6 non-null      object 
dtypes: float64(2), object(4)
memory usage: 416.0+ bytes


In [5]:
df.isnull()

size  color  gender  price  weight  bought
0  False  False   False  False   False   False
1  False  False   False  False   False   False
2  False  False    True   True   False   False
3   True  False   False  False    True   False
4  False  False   False  False   False   False
5  False  False   False  False    True   False

In [6]:
df.isnull().sum()

size      1
color     0
gender    1
price     1
weight    2
bought    0
dtype: int64

In [7]:
df.isnull().sum().sum()

5

In [9]:
df.isnull().sum()/len(df)*100

size      16.666667
color      0.000000
gender    16.666667
price     16.666667
weight    33.333333
bought     0.000000
dtype: float64

In [13]:
df['weight']

0    500.0
1    450.0
2    300.0
3      NaN
4    410.0
5      NaN
Name: weight, dtype: float64

In [15]:
from sklearn.impute import SimpleImputer
# strategy: 'mean', 'median', 'most_frequent', 'constant'
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(df[['weight']])

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='mean', verbose=0)

In [16]:
imputer.statistics_

array([415.])

In [17]:
imputer.transform(df[['weight']])

array([[500.],
       [450.],
       [300.],
       [415.],
       [410.],
       [415.]])

In [0]:
df['weight'] = imputer.transform(df[['weight']])

In [19]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0   415.0     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0   415.0     no

In [20]:
imputer_price = SimpleImputer(missing_values=np.nan, strategy='constant',fill_value=99.0)
imputer_price.fit_transform(df[['price']])

array([[199.],
       [ 89.],
       [ 99.],
       [129.],
       [ 79.],
       [ 89.]])

In [21]:
imputer_size = SimpleImputer(missing_values=np.nan, strategy='constant',fill_value='L')
imputer_size.fit_transform(df[['size']])

array([['XL'],
       ['L'],
       ['M'],
       ['L'],
       ['M'],
       ['M']], dtype=object)

In [22]:
imputer_size = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
imputer_size.fit_transform(df[['size']])

array([['XL'],
       ['L'],
       ['M'],
       ['M'],
       ['M'],
       ['M']], dtype=object)

In [23]:
df = df_raw.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

In [24]:
df.isnull().sum()

size      1
color     0
gender    1
price     1
weight    2
bought    0
dtype: int64

In [28]:
weight_isnull = pd.isnull(df['weight'])
df[weight_isnull]

size  color  gender  price  weight bought
3  NaN  green  female  129.0     NaN     no
5    M  green    male   89.0     NaN     no

In [29]:
df[~weight_isnull]

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
4    M    red  female   79.0   410.0    yes

In [0]:
weight_notnull = pd.notnull(df['weight'])

In [31]:
df[weight_notnull]

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
4    M    red  female   79.0   410.0    yes

In [32]:
df[~weight_notnull]

size  color  gender  price  weight bought
3  NaN  green  female  129.0     NaN     no
5    M  green    male   89.0     NaN     no

In [33]:
df.fillna(value='brak')

size  color  gender price weight bought
0    XL    red  female   199    500    yes
1     L  green    male    89    450     no
2     M   blue    brak  brak    300    yes
3  brak  green  female   129   brak     no
4     M    red  female    79    410    yes
5     M  green    male    89   brak     no

In [34]:
df.fillna(value=0.0)

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue       0    0.0   300.0    yes
3    0  green  female  129.0     0.0     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     0.0     no

In [35]:
df['size']

0     XL
1      L
2      M
3    NaN
4      M
5      M
Name: size, dtype: object

In [37]:
df['size'].fillna(value='L')

0    XL
1     L
2     M
3     L
4     M
5     M
Name: size, dtype: object

In [38]:
df.dropna()

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
4    M    red  female   79.0   410.0    yes

In [41]:
df.dropna(thresh=1)

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no

In [40]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue     NaN    NaN   300.0    yes
3  NaN  green  female  129.0     NaN     no
4    M    red  female   79.0   410.0    yes
5    M  green    male   89.0     NaN     no